FROM node:10 as build-client   

WORKDIR /usr/src/app

COPY ./client/package.json .
COPY ./client/package-lock.json .

RUN npm ci

COPY ./client . 
RUN npm run build


FROM nginx

COPY --from=build-client /usr/src/app/dist /usr/share/nginx/html/bot-generator-ui

COPY ./nginx.conf.template /etc/nginx/conf.d/default.conf

EXPOSE 80